name: Run Pytest 3.6

on:
  push:
    branches:
      - main
    paths:
      - 'vectorhub/**'
      - 'tests/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    # paths:
    #   - 'vectorhub/**'
    #   - 'tests/**'
    #   - 'setup.py'

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pytest 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install base dependencies
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install dependencies for tests
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -r requirements.txt
          pip install -e ".[test]"

      - name: Test Vectorai models
        env:
            VI_USERNAME: ${{ secrets.VI_USERNAME }}
            VI_API_KEY: ${{ secrets.VI_API_KEY }}
        run: |
          pytest tests/encoders/text/vectorai

      - name: Test cases text transformers
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-text-tf-transformers]"
          pip install -e ".[encoders-text-torch-transformers]"
          pytest tests/encoders/text/tf_transformers
          pytest tests/encoders/text/torch_transformers

      - name: Install & Test for text tfhub
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-text-tfhub]"
          pytest tests/encoders/text/tfhub/test_albert.py
          pytest tests/encoders/text/tfhub/test_bert.py
          pytest tests/encoders/text/tfhub/test_labse.py

      - name: Install & Test for text sentence transformers
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-text-sentence-transformers]"
          pytest tests/encoders/text/sentence_transformers

      - name: Install dependencies and test bi-encoders tf-text-hub
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-text-tfhub]"
          pytest tests/bi_encoders/text_text/tfhub
      
      - name: Test cases for Autoencoder
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pytest -v -m text

      - name: Install & Test for text tfhub
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-text-tfhub]"
          pytest tests/encoders/text/tfhub/test_use.py
          pytest tests/encoders/text/tfhub/test_elmo.py
