name: Run Pytest 3.6 Audio

on:
  push:
    branches:
      - main
    paths:
      - 'vectorhub/**'
      - 'tests/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    # paths:
    #   - 'vectorhub/**'
    #   - 'tests/**'
    #   - 'setup.py'

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pytest 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install base dependencies
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install dependencies for tests
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -r requirements.txt
          pip install -e ".[test]"
      - name: Test Vectorai models
        env:
            VI_USERNAME: ${{ secrets.VI_USERNAME }}
            VI_API_KEY: ${{ secrets.VI_API_KEY }}
        run: |
          pytest tests/encoders/audio/vectorai
      - name: Install dependencies and test for audio tfhub
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          
          pip install -e ".[encoders-audio-tfhub]"
          pytest tests/encoders/audio/tfhub

      - name: Install and Test cases for encoders-audio-pytorch
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-audio-pytorch]"
          pytest tests/encoders/audio/pytorch

      - name: Test cases for Autoencoder
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pytest -v -m audio
